# Support Vector Machine (Destek Vektör Makineleri)

In [13]:
#Kütüphanelerin eklenmesi
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pandas_profiling

In [14]:
#Veri setinin import edilmesi
dataset = pd.read_csv('sigorta.csv', encoding = 'iso-8859-9')

In [11]:
data_profile = pd.read_csv('sigorta.csv', encoding = 'iso-8859-9').profile_report()
data_profile

In [15]:
X = dataset.iloc[:, 0:6].values
y = dataset.iloc[:, 6].values
y = y.reshape(-1, 1) 

In [17]:
from sklearn.preprocessing import LabelEncoder 
labelencoder = LabelEncoder()
X[:, 1] = labelencoder.fit_transform(X[:, 1]) 

X[:, 4] = labelencoder.fit_transform(X[:, 4])

X[:, 5] = labelencoder.fit_transform(X[:, 5])


In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 0 0 0]
 [1.0 0.0 1.0 ... 1 1 1]
 [1.0 0.0 1.0 ... 3 1 1]
 ...
 [0.0 1.0 0.0 ... 0 1 1]
 [0.0 1.0 0.0 ... 0 1 0]
 [0.0 1.0 0.0 ... 0 0 2]]


In [21]:
# Veri setinin eğitim ve test olarak bölümlenmesi
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [22]:
# Özellik ölçekleme (Feature Scaling)
# SVR algoritması ölçeklenmiş veri ister !
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)
y_train_scale = scaler.fit_transform(y_train) 
y_test_scale = scaler.fit_transform(y_test) 

In [23]:
# SVR fit : SVR parametreleri derste anlatildi biz varsayalini kullanacagiz
# parameter tuning de her parametre icin ornegin GridsearchCV ile optimizasyon yapilabilir..
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train_scale, y_train_scale)
y_pred_scale = regressor.predict(X_test_scale)

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test_scale, y_pred_scale)

0.7620142082653782

In [25]:
y_pred_scale = y_pred_scale.reshape(-1, 1)
y_predGercek = scaler.inverse_transform(y_pred_scale)

In [26]:
#verileri ölçeklemeden modeli eğitelim ve test edelim

from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)
y_predOlceksiz = regressor.predict(X_test)

In [27]:
#r2 değerinin veriler ölçeksiz olduğundaki durumunu görelim.
#r2 değerinin negatif çıkması modelin başarısının çok kötü olduğu anlamına gelmektedir.
from sklearn.metrics import r2_score
r2_score(y_test, y_predOlceksiz)

-0.10381189273389446